### ISSUE TITLE
Missing creation panel after maya crash while moving panels

### ISSUE THREAD

**Issue by Muream** [HolisticCoders/icarus#105]
Here's the error:
```
# RuntimeError: Internal C++ object (PySide2.QtWidgets.QFormLayout) already deleted.
# Traceback (most recent call last):
#   File "C:/Users/Brendan/Documents/maya/2018/scripts\icarus\ui\signals.py", line 58, in publish
#     res = func(*args, **kwargs)
#   File "C:/Users/Brendan/Documents/maya/2018/scripts\icarus\ui\module.py", line 92, in _on_selection_changed
#     self._update_ui()
#   File "C:/Users/Brendan/Documents/maya/2018/scripts\icarus\ui\module.py", line 245, in _update_ui
#     clear_layout(self.form)
#   File "C:/Users/Brendan/Documents/maya/2018/scripts\icarus\ui\utils.py", line 2, in clear_layout
#     item = layout.takeAt(0)
# RuntimeError: Internal C++ object (PySide2.QtWidgets.QFormLayout) already deleted.
```
Removing the preference file fixed the issue.
Maybe ignore the reset window layout if we get this error?

**Comment by niuzhenjiang** [comment]
> 这是错误：
> 
> ```
> # RuntimeError: Internal C++ object (PySide2.QtWidgets.QFormLayout) already deleted.
> # Traceback (most recent call last):
> #   File "C:/Users/Brendan/Documents/maya/2018/scripts\icarus\ui\signals.py", line 58, in publish
> #     res = func(*args, **kwargs)
> #   File "C:/Users/Brendan/Documents/maya/2018/scripts\icarus\ui\module.py", line 92, in _on_selection_changed
> #     self._update_ui()
> #   File "C:/Users/Brendan/Documents/maya/2018/scripts\icarus\ui\module.py", line 245, in _update_ui
> #     clear_layout(self.form)
> #   File "C:/Users/Brendan/Documents/maya/2018/scripts\icarus\ui\utils.py", line 2, in clear_layout
> #     item = layout.takeAt(0)
> # RuntimeError: Internal C++ object (PySide2.QtWidgets.QFormLayout) already deleted.
> ```
> 
> 删除首选项文件修复了该问题。
> 如果我们收到此错误，可能会忽略重置窗口布局？

你好，我也遇到这个问题，请问你是如何解决的？？

**Comment by Muream** [comment]
@niuzhenjiang English please, we can't help you otherwise.

**Comment by niuzhenjiang** [comment]
> @niuzhenjiang英文请，我们不能帮助你。

sorry,I mean, I also encountered this problem. How can you solve it? Can you elaborate on it? Thank you.

**Comment by Muream** [comment]
Try to delete the content of `C:\Users\Brendan\AppData\Roaming\Holistic Coders` and restart maya.
This isn't ideal but should do the trick for now
