### ISSUE TITLE
Issue when reparenting multiple modules of the same module tree

### ISSUE THREAD

**Issue by Aphosis** [HolisticCoders/icarus#127]
```
# Traceback (most recent call last):
#   File "/home/jongjong/maya/scripts/mop/ui/signals.py", line 58, in publish
#     res = func(*args, **kwargs)
#   File "/home/jongjong/maya/scripts/mop/ui/rig.py", line 206, in _on_modules_updated
#     was_renamed = self._handle_renaming(module, module_item)
#   File "/home/jongjong/maya/scripts/mop/ui/rig.py", line 228, in _handle_renaming
#     was_renamed = module_item.text() != module_name
# RuntimeError: Internal C++ object (PySide2.QtGui.QStandardItem) already deleted.
```

**Comment by Aphosis** [comment]
Fixed by 25ec8f22f2191c87ae41d5980430917749723b98.
